# Generated by Django 6.0.2 on 2026-02-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='typing/')),
                ('duration', models.IntegerField(choices=[(15, '15 Seconds'), (30, '30 Seconds'), (60, '60 Seconds')])),
            ],
        ),
    ]
