# Generated by Django 6.0.2 on 2026-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_test', '0002_imageinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageinfo',
            name='duration',
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='time_limit',
            field=models.IntegerField(default=60),
        ),
    ]
