# Generated by Django 6.0.2 on 2026-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_test', '0003_remove_imageinfo_duration_imageinfo_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingresult',
            name='time_limit',
            field=models.IntegerField(default=60),
        ),
    ]
