# Generated by Django 6.0.2 on 2026-02-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_test', '0004_typingresult_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingresult',
            name='test_time',
            field=models.IntegerField(default=60),
        ),
    ]
